import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const chatGuardianStyles = StyleSheet.create({
  chatGuardianBoard: {
    flexDirection: 'row',
    gap: 12,
    minHeight: 420,
  },
  chatGuardianContactsPanel: {
    flex: 0.36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    padding: 14,
    gap: 12,
  },
  chatGuardianPanelEyebrow: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  chatGuardianContactsList: {
    gap: 10,
  },
  chatGuardianContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    padding: 10,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  chatGuardianContactRowActive: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: '#dbeafe',
    shadowColor: colors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  chatGuardianContactAvatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: '#d1d5db',
  },
  chatGuardianContactAvatar: {
    fontSize: 18,
  },
  chatGuardianContactTextWrap: {
    flex: 1,
    gap: 2,
  },
  chatGuardianContactName: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '800',
  },
  chatGuardianContactSubtitle: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  chatGuardianThreatDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  chatGuardianThreatSafe: {
    backgroundColor: '#22c55e',
  },
  chatGuardianThreatWarning: {
    backgroundColor: '#f59e0b',
  },
  chatGuardianThreatDanger: {
    backgroundColor: '#ef4444',
  },
  chatGuardianChatPanel: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    overflow: 'hidden',
  },
  chatGuardianHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.35)',
    backgroundColor: colors.surface,
  },
  chatGuardianHeaderTextWrap: {
    flex: 1,
    gap: 4,
  },
  chatGuardianHeadline: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  chatGuardianIntro: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
  },
  chatGuardianThreatChip: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#6366f1',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 2,
    borderColor: '#4f46e5',
    shadowColor: '#6366f1',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  chatGuardianThreatChipText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  chatGuardianThread: {
    padding: 14,
    gap: 10,
    minHeight: 240,
    backgroundColor: 'linear-gradient(180deg, #fafafa 0%, #ffffff 100%)',
  },
  chatGuardianMessageBubble: {
    maxWidth: '86%',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  chatGuardianMessageIncoming: {
    alignSelf: 'flex-start',
    backgroundColor: '#dbeafe',
    borderTopLeftRadius: 6,
  },
  chatGuardianMessageOutgoing: {
    alignSelf: 'flex-end',
    backgroundColor: '#e0f2fe',
    borderTopRightRadius: 6,
  },
  chatGuardianMessageSender: {
    color: '#1e293b',
    fontSize: 11,
    fontWeight: '800',
  },
  chatGuardianMessageText: {
    color: '#0f172a',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  chatGuardianMessageTime: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '700',
  },
  chatGuardianAlertBox: {
    marginHorizontal: 14,
    marginBottom: 12,
    borderRadius: 14,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: '#f59e0b',
    backgroundColor: '#fef3c7',
    padding: 12,
    gap: 6,
    shadowColor: '#f59e0b',
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  chatGuardianAlertTitle: {
    color: '#78350f',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  chatGuardianAlertList: {
    gap: 4,
  },
  chatGuardianAlertItem: {
    color: '#b45309',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  chatGuardianActionPrompt: {
    marginHorizontal: 14,
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  chatGuardianActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: 14,
    paddingBottom: 14,
  },
  chatGuardianActionButton: {
    flexBasis: '48%',
    minWidth: 140,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    paddingHorizontal: 10,
    gap: 4,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  chatGuardianActionButtonSelected: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: '#dbeafe',
    shadowColor: colors.accent,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  chatGuardianActionButtonCorrect: {
    borderColor: '#22c55e',
    borderWidth: 3,
    backgroundColor: '#dcfce7',
    shadowColor: '#22c55e',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  chatGuardianActionButtonWrong: {
    borderColor: '#ef4444',
    borderWidth: 3,
    backgroundColor: '#fee2e2',
    shadowColor: '#ef4444',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  chatGuardianActionIcon: {
    fontSize: 18,
  },
  chatGuardianActionTitle: {
    color: '#1f2937',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 18,
  },
  chatGuardianActionTitleSelected: {
    color: '#0369a1',
    fontWeight: '900',
  },
  chatGuardianActionHint: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  chatGuardianActionHintSelected: {
    color: '#0284c7',
    fontWeight: '800',
  },
  chatGuardianTypingBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#dbeafe',
    borderTopLeftRadius: 6,
    maxWidth: '86%',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chatGuardianTypingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#0369a1',
    marginHorizontal: 2,
  },
});
