import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const firewallStyles = StyleSheet.create({
  firewallBoard: {
    flexDirection: 'row',
    gap: 12,
    userSelect: 'none',
  },
  firewallBoardStacked: {
    flexDirection: 'column',
  },
  firewallMainPanel: {
    flex: 1,
    gap: 10,
    userSelect: 'none',
  },
  firewallTopbar: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    userSelect: 'none',
  },
  firewallStat: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  firewallShieldWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  firewallShieldTrack: {
    width: 110,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#d1d5db',
    overflow: 'hidden',
  },
  firewallShieldFill: {
    height: '100%',
    backgroundColor: '#22c55e',
  },
  firewallShieldText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '800',
  },
  firewallArena: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#eff6ff',
    minHeight: 500,
    padding: 12,
    userSelect: 'none',
  },
  firewallArenaGlow: {
    position: 'absolute',
    inset: 0,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  firewallStar: {
    position: 'absolute',
    borderRadius: 999,
    backgroundColor: '#ffffff',
  },
  firewallBubble: {
    width: 56,
    height: 56,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    position: 'absolute',
  },
  firewallThreatBubble: {
    backgroundColor: '#fecaca',
    borderWidth: 1,
    borderColor: '#fca5a5',
    marginTop: 8,
  },
  firewallDataBubble: {
    backgroundColor: '#bfdbfe',
    borderWidth: 1,
    borderColor: '#93c5fd',
    marginTop: 18,
  },
  firewallPowerBubble: {
    backgroundColor: '#fde68a',
    borderWidth: 1,
    borderColor: '#fbbf24',
    marginTop: 18,
  },
  firewallBubbleIcon: {
    fontSize: 24,
  },
  firewallBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 10,
  },
  firewallPirateCard: {
    position: 'absolute',
    borderRadius: 14,
    backgroundColor: '#f472b6',
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 170,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    userSelect: 'none',
  },
  firewallPirateTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  firewallPirateText: {
    color: '#fdf2f8',
    fontSize: 12,
    marginTop: 2,
    fontWeight: '700',
  },
  firewallCoffreCard: {
    position: 'absolute',
    bottom: 14,
    width: 120,
    borderRadius: 999,
    backgroundColor: '#60a5fa',
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'center',
    zIndex: 3,
    elevation: 4,
    userSelect: 'none',
  },
  firewallCoffreTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  firewallCoffreHint: {
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
  },
  firewallQuestionCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 10,
  },
  firewallQuestionModule: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  firewallQuestionPrompt: {
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '800',
  },
  firewallControlsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  firewallControlButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  firewallControlPrimary: {
    borderColor: '#4f46e5',
    backgroundColor: '#4f46e5',
  },
  firewallControlText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
  },
  firewallControlTextPrimary: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  firewallGameStateText: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '700',
  },
  firewallSafeMarker: {
    position: 'absolute',
    right: 14,
    bottom: 8,
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#10b981',
    opacity: 0.12,
  },
  firewallTouchpad: {
    display: 'flex',
    gap: 8,
    justifyContent: 'center',
    marginTop: 8,
    flexDirection: 'row',
  },
  firewallTouchButton: {
    width: 110,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    alignItems: 'center',
    justifyContent: 'center',
    userSelect: 'none',
  },
  firewallTouchButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  firewallOptionsWrap: {
    gap: 8,
  },
  firewallOptionButton: {
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#94a3b8',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  firewallOptionButtonSelected: {
    borderColor: '#3b82f6',
    backgroundColor: '#dbeafe',
  },
  firewallOptionButtonCorrect: {
    borderColor: '#16a34a',
    backgroundColor: '#dcfce7',
  },
  firewallOptionButtonWrong: {
    borderColor: '#dc2626',
    backgroundColor: '#fee2e2',
  },
  firewallOptionText: {
    color: '#1f2937',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
  },
  firewallSidePanel: {
    width: 550,
    gap: 10,
    flexDirection: 'row',
  },
  firewallSidePanelStacked: {
    width: '100%',
    flexDirection: 'column',
  },
  firewallSideCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    padding: 12,
    gap: 8,
    flex: 1,
  },
  firewallSideTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  firewallInventoryGrid: {
    gap: 6,
  },
  firewallInventoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  firewallInventoryLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  firewallInventoryTag: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '700',
  },
  firewallInventoryTagSafe: {
    borderColor: '#bbf7d0',
    backgroundColor: '#ecfdf5',
    color: '#065f46',
  },
  firewallInventoryTagLeaked: {
    borderColor: '#fecaca',
    backgroundColor: '#fee2e2',
    color: '#991b1b',
  },
  firewallLegendList: {
    gap: 6,
  },
  firewallLegendItem: {
    color: '#12486c',
    fontSize: 14,
    fontWeight: '600',
  },
  firewallLegendTip: {
    color: '#12486c',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
});
