import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';

export const quizClassicStyles = StyleSheet.create({
  questionCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 14,
    gap: 12,
  },
  questionEventCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    padding: 12,
    gap: 10,
  },
  questionEventHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  questionEventIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e0e7ff',
  },
  questionEventIcon: {
    fontSize: 20,
  },
  questionEventTitle: {
    flex: 1,
    color: '#1e293b',
    fontSize: 18,
    fontWeight: '800',
  },
  questionEventContext: {
    color: '#334155',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  questionEventMessageBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#eef2f7',
    padding: 12,
  },
  questionEventMessage: {
    color: '#374151',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '600',
  },
  questionTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  questionMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  optionsWrap: {
    gap: 8,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: 12,
    paddingVertical: 11,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  optionItemSelected: {
    borderColor: colors.accent,
    borderWidth: 3,
    backgroundColor: '#1e3a8a',
    shadowColor: colors.accent,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  optionItemCorrect: {
    borderColor: '#22c55e',
    borderWidth: 3,
    backgroundColor: '#166534',
    shadowColor: '#22c55e',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  optionItemWrong: {
    borderColor: '#ef4444',
    borderWidth: 3,
    backgroundColor: '#7f1d1d',
    shadowColor: '#ef4444',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 6,
  },
  optionIndex: {
    width: 24,
    height: 24,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: '#d1d5db',
    color: '#4b5563',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 12,
    fontWeight: '800',
  },
  optionIndexSelected: {
    borderColor: colors.accent,
    borderWidth: 3,
    color: '#ffffff',
    backgroundColor: colors.accent,
  },
  optionIndexCorrect: {
    borderColor: '#22c55e',
    borderWidth: 3,
    color: '#ffffff',
    backgroundColor: '#22c55e',
  },
  optionIndexWrong: {
    borderColor: '#ef4444',
    borderWidth: 3,
    color: '#ffffff',
    backgroundColor: '#ef4444',
  },
  optionText: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    lineHeight: 19,
  },
  optionTextSelected: {
    color: '#ffffff',
    fontWeight: '700',
  },
  feedbackCard: {
    borderRadius: 12,
    borderWidth: 2,
    padding: 12,
    gap: 6,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  feedbackCardSuccess: {
    borderColor: '#22c55e',
    backgroundColor: '#166534',
  },
  feedbackCardError: {
    borderColor: '#ef4444',
    backgroundColor: '#7f1d1d',
  },
  feedbackTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  feedbackBody: {
    color: '#e8f5e9',
    fontSize: 13,
    lineHeight: 19,
  },
  timeWarningCard: {
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#fbbf24',
    backgroundColor: '#78350f',
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: '#fbbf24',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  timeWarningText: {
    color: '#fef3c7',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
});
